sudo: required

services: docker

bofore_install:
  - docker-compose up --build -d

script:
  - docker_compose exec --env 'RAILS_ENV=test' web rails db:create
  - docker_compose exec --env 'RAILS_ENV=test' web rails db:migrate
  - docker_compose exec --env 'RAILS_ENV=test' web rails test
